config:
  validation: true
  warningsAsErrors: false

comments:
  active: true
  excludes: [ '**/test/**' ]
  AbsentOrWrongFileLicense:
    active: false
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  DeprecatedBlockTag:
    active: true
  EndOfSentenceFormat:
    active: false
  KDocReferencesNonPublicProperty:
    active: false
  OutdatedDocumentation:
    active: false
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false

complexity:
  active: true
  excludes: [ '**/test/**' ]
  CognitiveComplexMethod:
    active: true
    allowedComplexity: 15
  ComplexCondition:
    active: false
    allowedConditions: 3
  ComplexInterface:
    active: false
    allowedDefinitions: 10
  CyclomaticComplexMethod:
    active: true
    allowedComplexity: 15
  LargeClass:
    active: false
    allowedLines: 600
  LongMethod:
    active: true
    allowedLines: 60
  LongParameterList:
    active: true
    allowedFunctionParameters: 6
    allowedConstructorParameters: 7
  MethodOverloading:
    active: false
  NamedArguments:
    active: false
  NestedBlockDepth:
    active: true
    allowedDepth: 4
  NestedScopeFunctions:
    active: false
    allowedDepth: 1
  StringLiteralDuplication:
    active: true
    allowedDuplications: 3
    ignoreStringsRegex: '(String|String\?)'
  TooManyFunctions:
    active: true
    allowedFunctionsPerFile: 11
    allowedFunctionsPerClass: 11
    allowedFunctionsPerInterface: 8
    allowedFunctionsPerObject: 8
    allowedFunctionsPerEnum: 8
    ignoreDeprecated: false
    ignorePrivate: false
    ignoreOverridden: false

coroutines:
  active: true
  CoroutineLaunchedInTestWithoutRunTest:
    active: false
  GlobalCoroutineUsage:
    active: false
  InjectDispatcher:
    active: true
    dispatcherNames: [ 'IO', 'Default', 'Unconfined' ]
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true
  SuspendFunInFinallySection:
    active: false
  SuspendFunSwallowedCancellation:
    active: false
  SuspendFunWithCoroutineScopeReceiver:
    active: false
  SuspendFunWithFlowReturnType:
    active: true

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: '^(_|ignore|expected)'
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: false
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKotlinFile:
    active: false
  EmptySecondaryConstructor:
    active: true
  EmptyTryBlock:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

exceptions:
  active: true
  ErrorUsageWithThrowable:
    active: false
  ExceptionRaisedInUnexpectedLocation:
    active: true
    methodNames: [ 'toString', 'hashCode', 'equals', 'finalize' ]
  InstanceOfCheckForException:
    active: true
    excludes: [ '**/test/**' ]
  NotImplementedDeclaration:
    active: true
  ObjectExtendsThrowable:
    active: true
  PrintStackTrace:
    active: true
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
    ignoreLabeled: false
  SwallowedException:
    active: true
    ignoredExceptionTypes: []
    allowedExceptionNameRegex: '^(_|ignore|expected)'
  ThrowingExceptionFromFinally:
    active: false
  ThrowingExceptionInMain:
    active: false
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
    exceptions: [ 'IllegalArgumentException', 'IllegalStateException', 'IOException' ]
  ThrowingNewInstanceOfSameException:
    active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames: [ 'ArrayIndexOutOfBoundsException', 'Error', 'Exception', 'IllegalMonitorStateException', 'NullPointerException', 'RuntimeException', 'Throwable' ]
    allowedExceptionNameRegex: '^(_|ignore|expected)'
  TooGenericExceptionThrown:
    active: true
    exceptionNames: [ 'Error', 'Exception', 'RuntimeException', 'Throwable' ]

naming:
  active: true
  BooleanPropertyNaming:
    active: false
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  ConstructorParameterNaming:
    active: true
    parameterPattern: '[a-z][a-zA-Z0-9]*|_'
    privateParameterPattern: '[a-z][a-zA-Z0-9]*|_'
    excludeClassPattern: '$^'
  EnumNaming:
    active: true
    enumEntryPattern: '[A-Z][a-zA-Z0-9_]*'
  ForbiddenClassName:
    active: false
  FunctionNameMaxLength:
    active: false
  FunctionNameMinLength:
    active: false
  FunctionNaming:
    active: true
    functionPattern: '([a-z][a-zA-Z0-9]*)|(`.*`)'
    excludeClassPattern: '$^'
  FunctionParameterNaming:
    active: true
    parameterPattern: '[a-z][a-zA-Z0-9]*|_'
    excludeClassPattern: '$^'
  InvalidPackageDeclaration:
    active: false
  MatchingDeclarationName:
    active: true
    mustBeFirst: true
  MemberNameEqualsClassName:
    active: true
    ignoreOverridden: true
  NoNameShadowing:
    active: true
  ObjectPropertyNaming:
    active: true
    constantPattern: '[A-Za-z][_A-Za-z0-9]*'
    propertyPattern: '[a-z][a-zA-Z0-9]*|_'
    privatePropertyPattern: '(_)?[a-z][a-zA-Z0-9]*|_'
  PackageNaming:
    active: true
    packagePattern: '^[a-z]+(\.[a-z][a-z0-9]*)*$'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'
    propertyPattern: '[a-z][a-zA-Z0-9]*|_'
    privatePropertyPattern: '_?[a-z][a-zA-Z0-9]*'
  VariableMaxLength:
    active: false
  VariableMinLength:
    active: false
  VariableNaming:
    active: true
    variablePattern: '[a-z][a-zA-Z0-9]*|_'
    privateVariablePattern: '(_)?[a-z][a-zA-Z0-9]*|_'
    excludeClassPattern: '$^'

performance:
  active: true
  ArrayPrimitive:
    active: true
  CouldBeSequence:
    active: false
    allowedOperations: 2
  ForEachOnRange:
    active: true
    excludes: [ '**/test/**' ]
  SpreadOperator:
    active: true
    excludes: [ '**/test/**' ]
  UnnecessaryPartOfBinaryExpression:
    active: true
  UnnecessaryTemporaryInstantiation:
    active: true
  UnnecessaryTypeCasting:
    active: false

potential-bugs:
  active: true
  AvoidReferentialEquality:
    active: false
    forbiddenTypePatterns: [ 'kotlin.String' ]
  CastNullableToNonNullableType:
    active: true
    ignorePlatformTypes: true
  CastToNullableType:
    active: true
  Deprecation:
    active: true
  DoubleMutabilityForCollection:
    active: false
  ElseCaseInsteadOfExhaustiveWhen:
    active: true
    ignoredSubjectTypes: []
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  ExplicitGarbageCollectionCall:
    active: true
  HasPlatformType:
    active: false
  IgnoredReturnValue:
    active: true
    restrictToConfig: true
    returnValueAnnotations: [ 'CheckResult', 'CheckReturnValue' ]
  ImplicitDefaultLocale:
    active: true
  ImplicitUnitReturnType:
    active: true
    allowExplicitReturnType: true
  InvalidRange:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  LateinitUsage:
    active: true
    excludes: [ '**/test/**' ]
    ignoreOnClassesPattern: ''
  MissingPackageDeclaration:
    active: false
    excludes: [ '**/test/**' ]
  NullCheckOnMutableProperty:
    active: true
  NullableToStringCall:
    active: true
  PropertyUsedBeforeDeclaration:
    active: true
  UnconditionalJumpStatementInLoop:
    active: false
  UnnecessaryNotNullCheck:
    active: true
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: false
  UnusedUnaryOperator:
    active: true
  UselessPostfixExpression:
    active: true
  WrongEqualsTypeParameter:
    active: true

style:
  active: true
  AbstractClassCanBeConcreteClass:
    active: false
  AbstractClassCanBeInterface:
    active: false
  BracesOnIfStatements:
    active: true
    singleLine: 'never'
    multiLine: 'always'
  BracesOnWhenStatements:
    active: false
    singleLine: false
    multiLine: true
  CanBeNonNullable:
    active: true
  CascadingCallWrapping:
    active: false
    includeElvis: true
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true
  DataClassContainsFunctions:
    active: false
  DataClassShouldBeImmutable:
    active: true
  DestructuringDeclarationWithTooManyEntries:
    active: true
    maxDestructuringEntries: 3
  DoubleNegativeLambda:
    active: false
  EqualsNullCall:
    active: true
  EqualsOnSignatureLine:
    active: false
  ExplicitCollectionElementAccessMethod:
    active: true
  ExplicitItLambdaParameter:
    active: true
  ForbiddenComment:
    active: false
  ForbiddenImport:
    active: false
  ForbiddenSuppress:
    active: false
  ForbiddenVoid:
    active: false
  LoopWithTooManyJumpStatements:
    active: true
    maxJumpCount: 5
  MagicNumber:
    active: true
    ignoreNumbers: [ '-1', '0', '1', '2' ]
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreLocalVariableDeclaration: true
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: true
    ignoreNamedArgument: true
  MandatoryBracesLoops:
    active: true
  MaxChainedCallsOnSameLine:
    active: true
    maxChainedCalls: 5
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
  ModifierOrder:
    active: true
  MultilineLambdaItParameter:
    active: true
  MultilineRawStringIndentation:
    active: true
    indentSize: 2
  NestedClassesVisibility:
    active: true
  NewLineAtEndOfFile:
    active: true
  NoTabs:
    active: true
  ObjectLiteralToLambda:
    active: true
  OptionalAbstractKeyword:
    active: true
  OptionalUnit:
    active: true
  ProtectedMemberInFinalClass:
    active: true
  RedundantExplicitType:
    active: true
  RedundantHigherOrderMapUsage:
    active: true
  ReturnCount:
    active: true
    max: 2
    excludeLabeled: false
    excludeReturnFromLambda: true
    excludeGuardClauses: false
  StringShouldBeRawString:
    active: true
  ThrowsCount:
    active: true
    max: 2
  UnnecessaryAnnotationUseSiteTarget:
    active: false
  UnnecessaryApply:
    active: true
  UnnecessaryBackticks:
    active: true
  UnnecessaryBracesAroundTrailingLambda:
    active: true
  UnnecessaryFilter:
    active: true
  UnnecessaryInheritance:
    active: true
  UnnecessaryInnerClass:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  UnderscoresInNumericLiterals:
    active: true
    acceptableLength: 5
    allowNonStandardGrouping: false
  UnusedParameter:
    active: true
    allowedNames: '_|ignore|expected'
  UnusedPrivateClass:
    active: true
  UnusedVariable:
    active: true
    allowedNames: '_|ignore|expected'
  UseAnyOrNoneInsteadOfFind:
    active: true
  UseArrayLiteralsInAnnotations:
    active: true
  UseCheckNotNull:
    active: true
  UseCheckOrError:
    active: true
  UseDataClass:
    active: false
  UseEmptyCounterpart:
    active: true
  UseIfEmptyOrIfBlank:
    active: true
  UseIfInsteadOfWhen:
    active: true
  UseLet:
    active: true
  UseOrEmpty:
    active: true
  UseRequire:
    active: true
  UseRequireNotNull:
    active: true
  UtilityClassWithPublicConstructor:
    active: false
  VarCouldBeVal:
    active: true
  WildcardImport:
    active: true
    excludeImports: [ 'java.util.*', 'kotlinx.android.synthetic.*' ]